#!/bin/bash

#Generieren Passwörter für CBL/BI-Admin User

pwd_cbladmin=$(echo $RANDOM | md5sum | head -c 20)
pwd_biadmin=$(echo $RANDOM | md5sum | head -c 20)

echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo neues Passwort für KeePass  cbladmin -> $pwd_cbladmin
echo neues Passwort für KeePass  biadmin ->  $pwd_biadmin
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

sudo chpasswd <<<"cbladmin:$pwd_cbladmin"
sudo chpasswd <<<"biadmin:$pwd_biadmin"